spring.datasource.url=jdbc:mysql://localhost:3306/birth_registration_db
spring.datasource.username=root
spring.datasource.password=Smita@6884

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081